In [1]:
import smote_variants as sv
import os
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import statistics
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from collections import Counter
import math
from sklearn.cluster import KMeans  
from sklearn import svm

/Users/emily/Desktop/Research/oversampling_python/venv/lib/python3.7/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [2]:
path = "/Users/emily/Desktop/Research/oversampling_python/data/"
folderName = 'yeast-2_vs_8-5-fold'#'abalone19-5-fold' # yeast6-5-fold'#'haberman-5-fold' #'abalone19-5-fold' # pima-5-fold yeast-2_vs_8-5-fold

os.chdir(path+ folderName)
dirs = os.listdir(path+ folderName)
train = []
test = []

for i in dirs:
    #print(i.split("-")[-1])
    if("xlsx" in i):
        if("tra" in i):
            train.append(i)

        elif("tst" in i):
            test.append(i)
train = sorted(train)
test = sorted(test)

In [3]:
data = pd.read_excel(train[0],index_col=0)

In [4]:
datanp = np.array(data)

In [5]:
X = data.iloc[:,:data.shape[1]-1]
y = data.iloc[:,data.shape[1]-1]

In [6]:
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [7]:
input_X = np.array(X)
input_X

array([[0.51, 0.4 , 0.56, ..., 0.5 , 0.49, 0.22],
       [0.4 , 0.42, 0.57, ..., 0.  , 0.53, 0.25],
       [0.46, 0.44, 0.52, ..., 0.  , 0.5 , 0.22],
       ...,
       [0.48, 0.61, 0.57, ..., 0.  , 0.45, 0.22],
       [0.71, 0.5 , 0.5 , ..., 0.  , 0.46, 0.22],
       [0.61, 0.48, 0.54, ..., 0.  , 0.5 , 0.22]])

In [8]:
input_X = pd.DataFrame(input_X)
y = pd.DataFrame(y)
allData= pd.concat([input_X,y],axis=1)
allData = np.array(allData)

In [12]:
from sklearn.cluster import AffinityPropagation
import numpy as np
clustering = AffinityPropagation(convergence_iter=2).fit(allData)
#X = np.array([[1, 2], [1, 4], [1, 0],
#              [4, 2], [4, 4], [4, 0]])
"""
clustering

clustering.labels_

clustering.predict([[0, 0], [4, 4]])

clustering.cluster_centers_
"""

/Users/emily/Desktop/Research/oversampling_python/venv/lib/python3.7/site-packages/sklearn/cluster/_affinity_propagation.py:154: FutureWarning: 'random_state' has been introduced in 0.23. It will be set to None starting from 1.0 (renaming of 0.25) which means that results will differ at every function call. Set 'random_state' to None to silence this warning, or to 0 to keep the behavior of versions <0.23.
  FutureWarning


'\nclustering\n\nclustering.labels_\n\nclustering.predict([[0, 0], [4, 4]])\n\nclustering.cluster_centers_\n'

In [13]:
clustering.cluster_centers_.size

342

In [17]:
clustering.cluster_centers_indices_

array([  0,   3,  31,  32,  62,  83,  91, 118, 122, 123, 135, 143, 149,
       164, 175, 190, 192, 200, 202, 215, 220, 221, 238, 240, 247, 250,
       272, 276, 280, 289, 323, 331, 336, 339, 343, 364, 379, 383])

In [21]:
len(clustering.cluster_centers_)

38